### ISSUE TITLE
Browser example

### ISSUE THREAD

**Issue by guest271314** [geekuillaume/node-speex-resampler#9]
Can you kindly create a browser-only example of the code?

**Comment by guest271314** [comment]
This is what I have tried so far https://plnkr.co/edit/cKW9SBDpbb8MyS8R?open=lib%2Fscript.js.

Either throws `'Chunk length should be a multiple of channels * 2 bytes'` in `processChunk()` or returns `undefined`.

**Comment by geekuillaume** [comment]
You added an empty `return;` statement instead of returning the correct buffer. Here's a working version of your example: https://plnkr.co/edit/OZRP3l2p7iDia90l?open=lib%2Fscript.js

**Comment by guest271314** [comment]
The output is distorted. What am I doing incorrectly?

```
      document.querySelector('input').onchange = async (e) => {
        const input = await e.target.files[0].slice(44).arrayBuffer();
        console.log('input:', input)
        const res = await resampler.processChunk(
          new Uint8Array(input)
        );
        var f = 
          new Float32Array(new Int16Array(res))
        ;
        var ac = new AudioContext({
        sampleRate:22050});

       var b = new AudioBuffer({
         length: f.length,
         numberOfChannels: 1,
         sampleRate: 22050
       });
       b.getChannelData(0).set(f);
       var s = new AudioBufferSourceNode(ac);
       s.buffer = b;
       var msd = new MediaStreamAudioDestinationNode(ac);
       s.connect(msd);
       var recorder = new MediaRecorder(msd.stream);
       recorder.ondataavailable = (e) => console.log(URL.createObjectURL(e.data));
       s.connect(ac.destination);
       s.onended = () => recorder.stop();
       recorder.start();
       s.start();
      };
```

[48000.wav.tar.gz](https://github.com/geekuillaume/node-speex-resampler/files/7563680/48000.wav.tar.gz)

[output.wav.tar.gz](https://github.com/geekuillaume/node-speex-resampler/files/7563766/output.wav.tar.gz)
